"""自动生成 —— 请勿手工编辑。来源: tools/genschema.py（实测本机 FreeRDP）。"""

# .rdp 键 -> 解析类型 ('i' / 's')。None 表示探针未能定出类型。
KEY_TYPE: dict[str, str | None] = {
    'selectedmonitors': 's',
    'winposstr': None,
    'devicestoredirect': 's',
    'drivestoredirect': 's',
    'kdcproxyname': 's',
    'endpointfedauth': 's',
    'gatewayaccesstoken': 's',
    'activityhint': 's',
    'hubdiscoverygeourl': 's',
    'diagnosticserviceurl': 's',
    'aadtenantid': 's',
    'armpath': 's',
    'wvd endpoint pool': 's',
    'resourceprovider': None,
    'gatewayhostname': 's',
    'shell working directory': 's',
    'alternate shell': 's',
    'remoteapplicationcmdline': 's',
    'remoteapplicationguid': 's',
    'remoteapplicationfile': 's',
    'remoteapplicationprogram': 's',
    'remoteapplicationicon': 's',
    'remoteapplicationname': 's',
    'loadbalanceinfo': 's',
    'camerastoredirect': 's',
    'usbdevicestoredirect': 's',
    'alternate full address': 's',
    'full address': 's',
    'password': 's',
    'domain': 's',
    'username': 's',
    'redirectwebauthn': 'i',
    'rdgiskdcproxy': 'i',
    'use redirection server name': None,
    'gatewaycredentialssource': None,
    'gatewayprofileusagemethod': None,
    'gatewayusagemethod': 'i',
    'disableremoteappcapscheck': 'i',
    'disableconnectionsharing': None,
    'remoteapplicationexpandworkingdir': None,
    'remoteapplicationexpandcmdline': None,
    'remoteapplicationmode': 'i',
    'enablerdsaadauth': 'i',
    'enablecredsspsupport': 'i',
    'negotiate security layer': 'i',
    'prompt for credentials': 'i',
    'promptcredentialonce': 'i',
    'authentication level': 'i',
    'public mode': None,
    'autoreconnect max retries': 'i',
    'autoreconnection enabled': 'i',
    'administrative session': 'i',
    'connect to console': 'i',
    'disableclipboardredirection': None,
    'disableprinterredirection': None,
    'redirectdirectx': None,
    'redirectposdevices': 'i',
    'redirectclipboard': 'i',
    'redirectsmartcards': 'i',
    'redirectlocation': 'i',
    'redirectcomports': 'i',
    'redirectprinters': 'i',
    'redirectdrives': 'i',
    'server port': 'i',
    'bitmapcachepersistenable': 'i',
    'bitmapcachesize': None,
    'disable cursor setting': None,
    'disable themes': 'i',
    'disable menu anims': 'i',
    'disable full window drag': 'i',
    'allow desktop composition': 'i',
    'allow font smoothing': 'i',
    'disable wallpaper': 'i',
    'enableworkspacereconnect': None,
    'workspaceid': None,
    'displayconnectionbar': None,
    'pinconnectionbar': None,
    'bandwidthautodetect': None,
    'networkautodetect': None,
    'connection type': 'i',
    'videoplaybackmode': 'i',
    'redirected video capture encoding quality': None,
    'encode redirected video capture': None,
    'audiocapturemode': 'i',
    'audioqualitymode': None,
    'audiomode': 'i',
    'disable ctrl+alt+del': None,
    'keyboardhook': 'i',
    'compression': 'i',
    'desktopscalefactor': 'i',
    'session bpp': 'i',
    'desktop size id': 'i',
    'desktopheight': 'i',
    'desktopwidth': 'i',
    'superpanaccelerationfactor': None,
    'enablesuperpan': None,
    'dynamic resolution': 'i',
    'smart sizing': 'i',
    'span monitors': 'i',
    'screen mode id': 'i',
    'singlemoninwindowedmode': None,
    'maximizetocurrentdisplays': None,
    'use multimon': 'i',
}

# .rdp 键 -> 它驱动的 FreeRDP settings 名列表（死键为空列表）
KEY_SETTINGS: dict[str, list[str]] = {
    'selectedmonitors': ['FreeRDP_NumMonitorIds'],
    'winposstr': [],
    'devicestoredirect': ['FreeRDP_DeviceRedirection'],
    'drivestoredirect': ['FreeRDP_DrivesToRedirect'],
    'kdcproxyname': ['FreeRDP_KerberosKdcUrl'],
    'endpointfedauth': ['FreeRDP_EndpointFedAuthToken'],
    'gatewayaccesstoken': ['FreeRDP_GatewayAccessToken'],
    'activityhint': ['FreeRDP_GatewayAvdActivityhint'],
    'hubdiscoverygeourl': ['FreeRDP_GatewayAvdHubdiscoverygeourl'],
    'diagnosticserviceurl': ['FreeRDP_GatewayAvdDiagnosticserviceurl'],
    'aadtenantid': ['FreeRDP_GatewayAvdAadtenantid'],
    'armpath': ['FreeRDP_GatewayAvdArmpath'],
    'wvd endpoint pool': ['FreeRDP_GatewayAvdWvdEndpointPool'],
    'resourceprovider': [],
    'gatewayhostname': ['FreeRDP_GatewayHostname'],
    'shell working directory': ['FreeRDP_ShellWorkingDirectory'],
    'alternate shell': ['FreeRDP_AlternateShell'],
    'remoteapplicationcmdline': ['FreeRDP_RemoteApplicationCmdLine'],
    'remoteapplicationguid': ['FreeRDP_RemoteApplicationGuid'],
    'remoteapplicationfile': ['FreeRDP_RemoteApplicationFile'],
    'remoteapplicationprogram': ['FreeRDP_RemoteApplicationProgram'],
    'remoteapplicationicon': ['FreeRDP_RemoteApplicationIcon'],
    'remoteapplicationname': ['FreeRDP_RemoteApplicationName'],
    'loadbalanceinfo': ['FreeRDP_LoadBalanceInfoLength'],
    'camerastoredirect': ['FreeRDP_DynamicChannelCount', 'FreeRDP_DynamicChannelArraySize'],
    'usbdevicestoredirect': ['FreeRDP_DynamicChannelCount', 'FreeRDP_DynamicChannelArraySize'],
    'alternate full address': ['FreeRDP_ServerHostname'],
    'full address': ['FreeRDP_ServerHostname'],
    'password': ['FreeRDP_Password'],
    'domain': ['FreeRDP_Domain'],
    'username': ['FreeRDP_Username'],
    'redirectwebauthn': ['FreeRDP_RedirectWebAuthN'],
    'rdgiskdcproxy': ['FreeRDP_KerberosRdgIsProxy'],
    'use redirection server name': [],
    'gatewaycredentialssource': [],
    'gatewayprofileusagemethod': [],
    'gatewayusagemethod': ['FreeRDP_GatewayUsageMethod', 'FreeRDP_GatewayEnabled', 'FreeRDP_GatewayBypassLocal'],
    'disableremoteappcapscheck': ['FreeRDP_DisableRemoteAppCapsCheck'],
    'disableconnectionsharing': [],
    'remoteapplicationexpandworkingdir': [],
    'remoteapplicationexpandcmdline': [],
    'remoteapplicationmode': ['FreeRDP_RemoteApplicationMode'],
    'enablerdsaadauth': ['FreeRDP_AadSecurity'],
    'enablecredsspsupport': ['FreeRDP_NlaSecurity'],
    'negotiate security layer': ['FreeRDP_NegotiateSecurityLayer'],
    'prompt for credentials': ['FreeRDP_PromptForCredentials'],
    'promptcredentialonce': ['FreeRDP_GatewayUseSameCredentials'],
    'authentication level': ['FreeRDP_AuthenticationLevel'],
    'public mode': [],
    'autoreconnect max retries': ['FreeRDP_AutoReconnectMaxRetries'],
    'autoreconnection enabled': ['FreeRDP_AutoReconnectionEnabled'],
    'administrative session': ['FreeRDP_ConsoleSession'],
    'connect to console': ['FreeRDP_ConsoleSession'],
    'disableclipboardredirection': [],
    'disableprinterredirection': [],
    'redirectdirectx': [],
    'redirectposdevices': ['FreeRDP_RedirectSerialPorts', 'FreeRDP_RedirectParallelPorts'],
    'redirectclipboard': ['FreeRDP_RedirectClipboard'],
    'redirectsmartcards': ['FreeRDP_RedirectSmartCards'],
    'redirectlocation': ['FreeRDP_DynamicChannelCount', 'FreeRDP_DynamicChannelArraySize'],
    'redirectcomports': ['FreeRDP_RedirectSerialPorts', 'FreeRDP_RedirectParallelPorts'],
    'redirectprinters': ['FreeRDP_RedirectPrinters'],
    'redirectdrives': ['FreeRDP_RedirectDrives'],
    'server port': ['FreeRDP_ServerPort'],
    'bitmapcachepersistenable': ['FreeRDP_BitmapCachePersistEnabled'],
    'bitmapcachesize': [],
    'disable cursor setting': [],
    'disable themes': ['FreeRDP_DisableThemes'],
    'disable menu anims': ['FreeRDP_DisableMenuAnims'],
    'disable full window drag': ['FreeRDP_DisableFullWindowDrag'],
    'allow desktop composition': ['FreeRDP_AllowDesktopComposition'],
    'allow font smoothing': ['FreeRDP_AllowFontSmoothing'],
    'disable wallpaper': ['FreeRDP_DisableWallpaper'],
    'enableworkspacereconnect': [],
    'workspaceid': [],
    'displayconnectionbar': [],
    'pinconnectionbar': [],
    'bandwidthautodetect': [],
    'networkautodetect': [],
    'connection type': ['FreeRDP_ConnectionType', 'FreeRDP_SupportGraphicsPipeline', 'FreeRDP_DisableFullWindowDrag', 'FreeRDP_DisableMenuAnims', 'FreeRDP_AllowDesktopComposition', 'FreeRDP_RemoteFxCodec', 'FreeRDP_GfxH264', 'FreeRDP_GfxAVC444', 'FreeRDP_GfxAVC444v2', 'FreeRDP_AllowFontSmoothing', 'FreeRDP_DisableWallpaper', 'FreeRDP_DisableThemes'],
    'videoplaybackmode': ['FreeRDP_SupportGeometryTracking', 'FreeRDP_SupportVideoOptimized'],
    'redirected video capture encoding quality': [],
    'encode redirected video capture': [],
    'audiocapturemode': ['FreeRDP_AudioCapture'],
    'audioqualitymode': [],
    'audiomode': ['FreeRDP_AudioPlayback', 'FreeRDP_RemoteConsoleAudio'],
    'disable ctrl+alt+del': [],
    'keyboardhook': ['FreeRDP_KeyboardHook'],
    'compression': ['FreeRDP_CompressionEnabled'],
    'desktopscalefactor': ['FreeRDP_DesktopScaleFactor'],
    'session bpp': ['FreeRDP_ColorDepth'],
    'desktop size id': ['FreeRDP_DesktopWidth', 'FreeRDP_DesktopHeight'],
    'desktopheight': ['FreeRDP_DesktopHeight'],
    'desktopwidth': ['FreeRDP_DesktopWidth'],
    'superpanaccelerationfactor': [],
    'enablesuperpan': [],
    'dynamic resolution': ['FreeRDP_SupportDisplayControl', 'FreeRDP_DynamicResolutionUpdate'],
    'smart sizing': ['FreeRDP_SmartSizing'],
    'span monitors': ['FreeRDP_SpanMonitors'],
    'screen mode id': ['FreeRDP_Fullscreen'],
    'singlemoninwindowedmode': [],
    'maximizetocurrentdisplays': [],
    'use multimon': ['FreeRDP_UseMultimon'],
}

# 需要特定取值才生效的键 -> 该取值
KEY_NEEDS_VALUE: dict[str, str] = {
    'selectedmonitors': 's:ZZTEST',
    'devicestoredirect': 's:ZZTEST',
    'drivestoredirect': 's:ZZTEST',
    'kdcproxyname': 's:ZZTEST',
    'endpointfedauth': 's:ZZTEST',
    'gatewayaccesstoken': 's:ZZTEST',
    'activityhint': 's:ZZTEST',
    'hubdiscoverygeourl': 's:ZZTEST',
    'diagnosticserviceurl': 's:ZZTEST',
    'aadtenantid': 's:ZZTEST',
    'armpath': 's:ZZTEST',
    'wvd endpoint pool': 's:ZZTEST',
    'gatewayhostname': 's:ZZTEST',
    'shell working directory': 's:ZZTEST',
    'alternate shell': 's:ZZTEST',
    'remoteapplicationcmdline': 's:ZZTEST',
    'remoteapplicationguid': 's:ZZTEST',
    'remoteapplicationfile': 's:ZZTEST',
    'remoteapplicationprogram': 's:ZZTEST',
    'remoteapplicationicon': 's:ZZTEST',
    'remoteapplicationname': 's:ZZTEST',
    'loadbalanceinfo': 's:ZZTEST',
    'camerastoredirect': 's:ZZTEST',
    'usbdevicestoredirect': 's:ZZTEST',
    'alternate full address': 's:ZZTEST',
    'full address': 's:ZZTEST',
    'password': 's:ZZTEST',
    'domain': 's:ZZTEST',
    'username': 's:ZZTEST',
    'redirectwebauthn': 'i:1',
    'rdgiskdcproxy': 'i:1',
    'gatewayusagemethod': 'i:1',
    'disableremoteappcapscheck': 'i:1',
    'remoteapplicationmode': 'i:1',
    'enablerdsaadauth': 'i:1',
    'enablecredsspsupport': 'i:0',
    'negotiate security layer': 'i:0',
    'prompt for credentials': 'i:1',
    'promptcredentialonce': 'i:1',
    'authentication level': 'i:0',
    'autoreconnect max retries': 'i:0',
    'autoreconnection enabled': 'i:1',
    'administrative session': 'i:1',
    'connect to console': 'i:1',
    'redirectposdevices': 'i:0',
    'redirectclipboard': 'i:0',
    'redirectsmartcards': 'i:1',
    'redirectlocation': 'i:1',
    'redirectcomports': 'i:1',
    'redirectprinters': 'i:1',
    'redirectdrives': 'i:1',
    'server port': 'i:0',
    'bitmapcachepersistenable': 'i:1',
    'disable themes': 'i:1',
    'disable menu anims': 'i:1',
    'disable full window drag': 'i:1',
    'allow desktop composition': 'i:0',
    'allow font smoothing': 'i:0',
    'disable wallpaper': 'i:1',
    'connection type': 'i:0',
    'videoplaybackmode': 'i:1',
    'audiocapturemode': 'i:1',
    'audiomode': 'i:0',
    'keyboardhook': 'i:0',
    'compression': 'i:0',
    'desktopscalefactor': 'i:0',
    'session bpp': 'i:0',
    'desktop size id': 'i:0',
    'desktopheight': 'i:0',
    'desktopwidth': 'i:0',
    'dynamic resolution': 'i:0',
    'smart sizing': 'i:1',
    'span monitors': 'i:1',
    'screen mode id': 'i:2',
    'use multimon': 'i:1',
}

# 在 FreeRDP 中无任何 effect 的键（28 个）
DEAD_KEYS: list[str] = ['audioqualitymode', 'bandwidthautodetect', 'bitmapcachesize', 'disable ctrl+alt+del', 'disable cursor setting', 'disableclipboardredirection', 'disableconnectionsharing', 'disableprinterredirection', 'displayconnectionbar', 'enablesuperpan', 'enableworkspacereconnect', 'encode redirected video capture', 'gatewaycredentialssource', 'gatewayprofileusagemethod', 'maximizetocurrentdisplays', 'networkautodetect', 'pinconnectionbar', 'public mode', 'redirectdirectx', 'redirected video capture encoding quality', 'remoteapplicationexpandcmdline', 'remoteapplicationexpandworkingdir', 'resourceprovider', 'singlemoninwindowedmode', 'superpanaccelerationfactor', 'use redirection server name', 'winposstr', 'workspaceid']
